{% set name = "tranquilizer" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0ca826ce6e0853c7a90573360de8c85ea6373045f260c13f38fd357d2bd0abd2

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - tranquilizer = tranquilizer.main:run

requirements:
  host:
    - python >=3.5, <3.9
    - pip
  run:
    - python >=3.5, <3.9
    - flask
    - werkzeug >=0.15, <1.0
    - flask-restplus
    - python-dateutil

test:
  imports:
    - tranquilizer
  commands:
    - tranquilizer --help

about:
  home: http://github.com/AlbertDeFusco/tranquilizer
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Put your Python functions to REST; deploy a REST API with one line by decorating your functions.'

extra:
  recipe-maintainers:
    - AlbertDeFusco
