{% set name = "tranquilizer" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/albertdefusco/{{ name }}/archive/{{ version }}.tar.gz
  sha256: f8f88bd9eeaf2cc1f55a8cbfbb886b672d9dc2feb2e57fdeccf145b0f9de033a

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - tranquilizer = tranquilizer.__main__:main

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - flask
    - werkzeug
    - flask-restplus
    - python-dateutil

test:
  imports:
    - tranquilizer
  commands:
    - tranquilizer --help

about:
  home: http://github.com/AlbertDeFusco/tranquilizer
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Put your Python functions to REST; deploy a REST API with one line by decorating your functions.'

extra:
  recipe-maintainers:
    - AlbertDeFusco
