{% set name = "tranquilizer" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/albertdefusco/{{ name }}/archive/{{ version }}.tar.gz
  sha256: f372db369004317b066f0767b605241c2f344d0f298002a514c0cc864a5a399c

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - tranquilizer = tranquilizer.__main__:main

requirements:
  host:
    - python >=3.5, <3.7
    - pip
  run:
    - python >=3.5, <3.7
    - flask
    - werkzeug <0.15
    - flask-restplus
    - python-dateutil

test:
  imports:
    - tranquilizer
  commands:
    - tranquilizer --help

about:
  home: http://github.com/AlbertDeFusco/tranquilizer
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Put your Python functions to REST; deploy a REST API with one line by decorating your functions.'

extra:
  recipe-maintainers:
    - AlbertDeFusco
