travis:
  secure:
    BINSTAR_TOKEN: I3f3ObZJ8c/9gNjtICm15TudnuH7PTWCKZv5TuFMTyxe0kGhaoNjQckDHd913R+K9VR/m82Pi7R7KENXbgwbe9+KKTluCQUD2ICFwoX7N1cLnOWMyGUoM6vLKbmden4P3+Zo+9yG+wtpFriViKWdFrExeSZOv6NnXWM+zD7oaE/02vtMiQFEIU9InAhKDuBOlMWw8RYV/v7yflp4kHbpXHhzpMvEQStQXpdADAEuDiu29dLr9+kUDGNhrIFJK358VSDT2HUqWBg5hdjYokzzm1wMt28PkrVvCVP9Z0u+TCA6Do4wRpWEwvtfFpEL0rPfaN1OxKRQCRVhkzsufqpeFMhp9yLhNdh2Uw0iS9Uy/B5xgGg2QmSSDCvOUyTJlXy+MZihUbbk6/Nrt0cBLvss2VyuL/nkI907E1Rgl93WevQYpXDalRB0vAfHCT5UbdDfvXujXYiQcggvtcpmiVkdNuzOB08A+v0DJBuAGYqnVz1DFcTGais5lC/2L7XdfzLRmOsC1J5bBlf6nDzAlEtBK7qQF5wF5A7UJhnWCIkFS1y4DOYwIKT3KVJzbMD975CnADHRYec9eVYuncGxnFPV5aM1iIDU4IqpX1YN0r4Zu/INSO5etvZYxrKo3W+aRzsZ2gIfO6zzcsKWdAYWuU0rs3yp5SYgr7BD48lnW4nI+Ws=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
